name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/tests.yml'
      - '**/*.swift'

jobs:
  tests-macos11:
    name: Test Builds - macOS 11
    runs-on: macos-11.0
    strategy:
      matrix:
        xcode: [ "12.4", "12.5.1", "13.0", "13.1", "13.2" ]

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: 🧱 Build
        run: make build-release

      - name: 🚩 Checkout Vexil
        uses: actions/checkout@v2
        with:
          repository: unsignedapps/Vexil
          ref: v1.2.2
          path: Vexil

      - name: 📦 Package Vexil
        run: cd Vexil && ../.build/release/swift-create-xcframework --zip --zip-version 1.2.2 --platform ios --platform macos --platform tvos --platform watchos

  tests-xcode-macos10_15:
    name: Test Builds - macOS 10.15
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [ "12.2", "12.3", "12.4" ]

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: 🧱 Build
        run: make build-release

      - name: 🚩 Checkout Vexil
        uses: actions/checkout@v2
        with:
          repository: unsignedapps/Vexil
          ref: v1.2.2
          path: Vexil

      - name: 📦 Package Vexil
        run: cd Vexil && ../.build/release/swift-create-xcframework --zip --zip-version 1.2.2 --platform ios --platform macos --platform tvos --platform watchos
